import bookmarksJson from "../../data/index/bookmarks.json";
import metaJson from "../../data/index/meta.json";
import { TOPICS, type TopicDefinition, type TopicSlug } from "./topics";
import type { IndexedBookmark, IndexMeta } from "./types";

/**
 * Read model for the site.
 *
 * `data/index/*.json` is generated by `npm run index` and committed, so page
 * rendering needs no database and no network. The files are imported (not read
 * from disk) so the bundler traces them into the serverless output.
 */

export const bookmarks = bookmarksJson as unknown as IndexedBookmark[];
export const indexMeta = metaJson as unknown as IndexMeta;

const byId = new Map(bookmarks.map((bookmark) => [bookmark.id, bookmark]));

export function getBookmark(id: string): IndexedBookmark | undefined {
  return byId.get(id);
}

export function getAllBookmarks(): IndexedBookmark[] {
  return bookmarks;
}

export function getRecentBookmarks(limit = 12): IndexedBookmark[] {
  return bookmarks.slice(0, limit);
}

export function getBookmarksByTopic(slug: string): IndexedBookmark[] {
  return bookmarks.filter((bookmark) => bookmark.topics.includes(slug));
}

export function getRelatedBookmarks(bookmark: IndexedBookmark, limit = 4): IndexedBookmark[] {
  return bookmark.related
    .map((id) => byId.get(id))
    .filter((related): related is IndexedBookmark => Boolean(related))
    .slice(0, limit);
}

export type TopicSummary = TopicDefinition & {
  count: number;
  /** Most common link domains in the topic, for the browse cards. */
  domains: string[];
  latest?: IndexedBookmark;
};

export function getTopicSummaries({ includeEmpty = false } = {}): TopicSummary[] {
  return TOPICS.map((topic) => {
    const entries = getBookmarksByTopic(topic.slug);
    const counts = new Map<string, number>();
    for (const entry of entries) {
      for (const link of entry.links) {
        if (link.domain) counts.set(link.domain, (counts.get(link.domain) ?? 0) + 1);
      }
    }
    return {
      ...topic,
      count: entries.length,
      domains: [...counts.entries()]
        .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
        .slice(0, 3)
        .map(([domain]) => domain),
      latest: entries[0],
    };
  }).filter((topic) => includeEmpty || topic.count > 0);
}

export function getTopic(slug: string): TopicSummary | undefined {
  return getTopicSummaries({ includeEmpty: true }).find((topic) => topic.slug === slug);
}

export type LibraryStats = {
  bookmarks: number;
  links: number;
  crawled: number;
  crawledWords: number;
  topics: number;
  authors: number;
  newest?: string;
  oldest?: string;
};

export function getStats(): LibraryStats {
  const links = new Set<string>();
  const crawled = new Set<string>();
  const authors = new Set<string>();
  let crawledWords = 0;

  for (const bookmark of bookmarks) {
    authors.add(bookmark.author.handle.toLowerCase());
    for (const link of bookmark.links) {
      links.add(link.url);
      if (link.crawl?.status === "ok") {
        crawled.add(link.url);
        crawledWords += link.crawl.word_count ?? 0;
      }
    }
  }

  const dates = bookmarks.map((bookmark) => bookmark.created_at).sort();
  return {
    bookmarks: bookmarks.length,
    links: links.size,
    crawled: crawled.size,
    crawledWords,
    topics: getTopicSummaries().length,
    authors: authors.size,
    newest: dates.at(-1),
    oldest: dates[0],
  };
}

/** Topic slugs ordered by how many bookmarks they hold, for nav and filters. */
export function getPopulatedTopicSlugs(): TopicSlug[] {
  return getTopicSummaries()
    .sort((a, b) => b.count - a.count)
    .map((topic) => topic.slug);
}
