import linksJson from "../../data/index/links.json";
import metaJson from "../../data/index/meta.json";
import { TOPICS, type TopicDefinition, type TopicSlug } from "./topics";
import type { IndexMeta, LibraryLink } from "./types";

/**
 * Read model for the site.
 *
 * `data/index/*.json` is generated by `npm run index` and committed, so page
 * rendering needs no database and no network. The files are imported (not read
 * from disk) so the bundler traces them into the serverless output.
 *
 * Every entry is an external site. Nothing from X is present here.
 */

export const links = linksJson as unknown as LibraryLink[];
export const indexMeta = metaJson as unknown as IndexMeta;

const byId = new Map(links.map((link) => [link.id, link]));

export function getLink(id: string): LibraryLink | undefined {
  return byId.get(id);
}

export function getAllLinks(): LibraryLink[] {
  return links;
}

export function getRecentLinks(limit = 12): LibraryLink[] {
  return links.slice(0, limit);
}

export function getLinksByTopic(slug: string): LibraryLink[] {
  return links.filter((link) => link.topics.includes(slug));
}

export function getRelatedLinks(link: LibraryLink, limit = 4): LibraryLink[] {
  return link.related
    .map((id) => byId.get(id))
    .filter((related): related is LibraryLink => Boolean(related))
    .slice(0, limit);
}

export type TopicSummary = TopicDefinition & {
  count: number;
  /** Most common domains in the topic, for the browse cards. */
  domains: string[];
  latest?: LibraryLink;
};

export function getTopicSummaries({ includeEmpty = false } = {}): TopicSummary[] {
  return TOPICS.map((topic) => {
    const entries = getLinksByTopic(topic.slug);
    const counts = new Map<string, number>();
    for (const entry of entries) {
      if (entry.domain) counts.set(entry.domain, (counts.get(entry.domain) ?? 0) + 1);
    }
    return {
      ...topic,
      count: entries.length,
      domains: [...counts.entries()]
        .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
        .slice(0, 3)
        .map(([domain]) => domain),
      latest: entries[0],
    };
  }).filter((topic) => includeEmpty || topic.count > 0);
}

export function getTopic(slug: string): TopicSummary | undefined {
  return getTopicSummaries({ includeEmpty: true }).find((topic) => topic.slug === slug);
}

export type LibraryStats = {
  links: number;
  domains: number;
  archived: number;
  words: number;
  topics: number;
  newest?: string;
  oldest?: string;
};

export function getStats(): LibraryStats {
  const domains = new Set<string>();
  let archived = 0;
  let words = 0;

  for (const link of links) {
    if (link.domain) domains.add(link.domain);
    if (link.status === "ok") {
      archived += 1;
      words += link.word_count;
    }
  }

  const dates = links.map((link) => link.saved_at).sort();
  return {
    links: links.length,
    domains: domains.size,
    archived,
    words,
    topics: getTopicSummaries().length,
    newest: dates.at(-1),
    oldest: dates[0],
  };
}

/** Topic slugs ordered by size, for nav and filters. */
export function getPopulatedTopicSlugs(): TopicSlug[] {
  return getTopicSummaries()
    .sort((a, b) => b.count - a.count)
    .map((topic) => topic.slug);
}
